# SPDX-FileCopyrightText: 2023 Norbert Melzer <timmelzer@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: "^Cargo.nix$"
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: forbid-submodules

  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
      - id: reuse

  - repo: local
    hooks:
      - id: cargo-fmt
        name: Cargo Format
        language: system
        files: ".*\\.rs$"
        entry: cargo fmt --check
        pass_filenames: false

      - id: alejandra
        name: Alejandra
        language: system
        files: ".*\\.nix$"
        exclude: "tests/nix-tests/.*\\.nix$"
        entry: nix fmt -- --check

      - id: cargo-audit
        name: Cargo Audit
        language: system
        always_run: true
        pass_filenames: false
        entry: cargo audit

      # Disable for now until there is more time to configure it
      - id: cargo-deny
        name: Cargo Deny
        language: system
        always_run: true
        pass_filenames: false
        entry: cargo deny check

      - id: coverage-validate
        name: Validate codecov.yml
        language: system
        files: "^codecov.yml$"
        entry: curl --data-binary @codecov.yml https://codecov.io/validate
        pass_filenames: false
        always_run: false

      - id: tests
        name: Run tests
        language: system
        files: ".*\\.rs"
        pass_filenames: false
        entry: cargo test --release

      # - id: doc-tests
      #   name: Run doctests
      #   language: system
      #   files: ".*\\.rs"
      #   pass_filenames: false
      #   entry: cargo test --doc
