# SPDX-FileCopyrightText: 2023 Norbert Melzer <timmelzer@gmailcom>
#
# SPDX-License-Identifier: CC0-1.0

name: checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  licenses:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ github.token }}
      - run: nix build --inputs-from . nixpkgs#reuse --no-link
      - run: nix shell --inputs-from . nixpkgs#reuse -c reuse lint

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ github.token }}
      - run: nix build --inputs-from . nixpkgs#alejandra .#rust --no-link
      - run: nix shell .#rust -c cargo fmt --check
      - run: nix fmt -- --check .

  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ github.token }}
      - run: nix build --inputs-from . nixpkgs#cargo-audit .#rust --no-link
      - run: nix shell --inputs-from . nixpkgs#cargo-audit .#rust -c cargo audit

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ github.token }}
      - run: nix build --inputs-from . nixpkgs#cargo-deny .#rust --no-link
      - run: nix shell --inputs-from . nixpkgs#cargo-deny .#rust -c cargo deny check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ github.token }}
      - run: nix build .#rust --no-link
      - run: nix shell .#rust -c cargo test --release

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ github.token }}
      - run: nix build .#rust --no-link
      - run: nix shell .#rust -c cargo build --release
